### ISSUE TITLE
Output page

### ISSUE THREAD

**Issue by AndrewLeinster** [AndrewLeinster/CW2-API-Mashup-Group-5#13]
We need to create a page to display the output of the API combinations.

Need to discuss format of output?

**Comment by AdamCMunro** [comment]
Is this still required or are we going to use the moreInfo.html page like you and I discussed, @AndrewLeinster

**Comment by AndrewLeinster** [comment]
> Is this still required or are we going to use the moreInfo.html page like you and I discussed, @AndrewLeinster

No, do as we discussed, will updates issue as per
